# Generated by Django 4.2.10 on 2024-02-24 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pretixbase", "0256_itemvariation_unavail_modes"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False
                    ),
                ),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="pretixbase.customer",
                    ),
                ),
                (
                    "giftcard",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="pretixbase.giftcard",
                    ),
                ),
            ],
        ),
    ]
